import React, { createContext, useState, useEffect, useContext } from 'react';

const translations = {
  en: {
    'nav.dashboard_title': 'Air Quality Monitoring Dashboard',
    'nav.live_data': 'Live Data',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.data_summary': 'Data Summary',
    'profile.user_name': 'Jahangir Mian',
    'filter.title': 'Filter',
    'filter.select_station': 'Select Station',
    'filter.all_stations': 'All Stations',
    'filter.select_parameter': 'Select Parameter',
    'filter.all_parameters': 'All Parameters',
    'live.graph_view': 'Graph View',
    'nav.summary': 'Summary',
    'nav.data_capture': 'Data Capture Rate',
    'nav.back_to_map': 'Back To Map',
    'profile.settings': 'Profile Settings',
    'profile.help': 'Help Center',
    'profile.logout': 'Logout',
    'live.title': 'Live Data',
    'live.view_type': 'View Type',
    'live.tabular_view': 'Tabular View',
    'live.map_view': 'Map View',
    'live.grid_view': 'Grid View',
    'live.stations': 'Stations',
    'live.city_centre': 'City Centre',
    'live.mobile_station': 'Mobile Station',
    'live.qidfa': 'Qidfa',
    'live.lafarge_cems': 'Lafarge Cems',
    'live.date': 'Date',
    'live.today': 'Today',
    'live.daily': 'Daily',
    'live.monthly': 'Monthly',
    'live.yearly': 'Yearly',
    'live.aqi_index': 'AQI Index',
    'live.moderate': 'Moderate',
    'live.live_aqi': 'Live AQI',
    'live.pollutant_metrics': 'Pollutant Metrics',
    'live.wind_speed': 'Wind Speed',
    'live.wind_direction': 'Wind Direction',
    'live.light_breeze': 'Light breeze',
    'live.temperature': 'Temperature',
    'live.ideal_temp': 'Ideal Temperature',
    'live.atmospheric_pressure': 'Atmospheric Pressure',
    'live.balanced_pressure': 'Balanced Air Pressure',
    'live.solar_radiation': 'Solar Radiation',
    'live.high_solar': 'High Solar Intensity',
    'live.relative_humidity': 'Relative Humidity',
    'live.humidity_normal': 'Humidity is normal',
    'live.fujairah': 'Fujairah',
    'analytics.parameters': 'Parameters',
    'analytics.report_type': 'Report Type',
    'analytics.daily_summary': 'Daily Summary',
    'analytics.hourly_summary': 'Hourly Summary',
    'analytics.min': 'Min',
    'analytics.max': 'Max',
    'analytics.avg': 'Avg',
    'analytics.download': 'Download',
    'datacapture.title': 'Data Capture Rate',
    'datacapture.tab1': 'Data Capture Rate',
    'datacapture.tab2': 'Valid Data Capture',
    'datacapture.collected_records': 'No.Of Collected Records',
    'datacapture.valid_records': 'No.Of Valid Records',
    'datacapture.sno': 'S.No',
    'datacapture.station_name': 'Station Name',
    'datacapture.parameter': 'Parameter',
    'datacapture.expected_records': 'No.Of Expected Records',
    'datacapture.percent_avail': 'Percent Availability',
    'login.title': 'Login',
    'login.subtitle': 'Please enter your details.',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.remember_me': 'Remember me',
    'login.forgot_password': 'Forgot password?',
    'login.no_account': "Don't have an account?",
    'login.sign_up': 'Sign up',
    'login.firstName': 'First Name',
    'login.lastName': 'Last Name',
    'login.phoneNumber': 'Phone Number',
    'login.emiratesId': 'Emirates ID',
    'login.emiratesIdPlaceholder': '784-XXXX-XXXXXXX-X',
    'login.firstNamePlaceholder': 'Enter First Name',
    'login.lastNamePlaceholder': 'Enter Last Name',
    'login.emailPlaceholder': 'Enter Email Address',
    'login.phoneNumberPlaceholder': 'Enter Phone Number',
    'login.joinPlatform': 'Join our platform',
    'login.createAnAccount': 'Create an Account',
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.forgotPasswordTitle': 'Forgot Password',
    'login.forgotPasswordSubtitle': 'Enter your email to receive an OTP code',
    'login.sendOtp': 'Send OTP',
    'login.backToLogin': 'Back to Login',
    'login.enterYourPasscode': 'Enter Verification Code',
    'login.otpSentSubtitle': 'We have sent a verification code to your email',
    'login.codeExpiresIn': 'Code expires in',
    'login.didNotReceiveCode': "Didn't receive the code?",
    'login.resendCode': 'Resend Code',
    'login.verify': 'Verify',
    'login.newPassword': 'New Password',
    'login.confirmPassword': 'Confirm Password',
    'login.updatePassword': 'Update Password',
    'login.resetPasswordTitle': 'Reset Password',
    'login.resetPasswordSubtitle': 'Enter your new password below',
    'dropdown.none': 'None',
    'landing.nav.our_air_quality': 'Our Air Quality',
    'landing.nav.live_air_quality': 'Live Air Quality',
    'landing.nav.contact_us': 'Contact Us',
    'landing.hero.title': 'Real-Time Air Quality Monitoring',
    'landing.hero.subtitle': 'for Fujairah Emirate',
    'landing.hero.view_live': 'View Live AQI',
    'landing.stats.current_aqi': 'Current AQI',
    'landing.stats.good': 'Good',
    'landing.stats.active_stations': 'Active Stations',
    'landing.stats.monitoring': 'Monitoring',
    'landing.stats.coverage_area': 'Coverage Area',
    'landing.stats.fujairah': 'Fujairah',
    'landing.map.title': 'Live Air Quality Map',
    'landing.map.desc': 'Explore real-time air quality metrics across the Fujairah Emirate.',
    'landing.map.city_centre': 'Stations',
    'landing.map.aqi_index': 'Air Quality Index',
    'landing.map.primary': 'Primary',
    'landing.map.secondary': 'Secondary',
    'landing.map.weather': 'Weather',
    'landing.map.last_updated': 'Last Updated',
    'landing.dash.safety_level': 'Air Quality Safety Level',
    'landing.dash.pollutant': 'Main Contributing Pollutant',
    'landing.dash.suburban': 'Suburban Traffic',
    'landing.dash.natural': 'Natural Sources',
    'landing.dash.causes': 'Possible Causes / Activities',
    'landing.dash.measures': 'Protective Measures',
    'landing.dash.trend': 'Hourly AQI Trend',
    'landing.dash.moderate': 'Moderate',
    'landing.dash.unhealthy_sg': 'Unhealthy for Sensitive Groups',
    'landing.dash.unhealthy': 'Unhealthy',
    'landing.dash.very_unhealthy': 'Very Unhealthy',
    'landing.dash.pm10': 'PM10 (Particulate Matter)',
    'landing.dash.respirable': 'Respirable dust',
    'landing.dash.measures.windows': 'Keep Windows Closed',
    'landing.dash.measures.outdoor': 'Reduce Outdoor Activity',
    'landing.dash.measures.mask': 'Wear N95 Mask',
    'landing.dash.measures.purifier': 'Use Air Purifier',
    'landing.footer.copyright': '© 2026 AQMS Fujairah. All rights reserved.',
    'landing.footer.terms': 'Terms of Service',
    'landing.footer.privacy': 'Privacy Policy',
    'landing.footer.support': 'Support',
    'chart.optimize_large_datasets': 'Optimize large datasets',
    'chart.showing_all_points': 'Showing all points',
    'chart.max_points_optimized': 'Max points (optimized)',
    'chart.marker': 'Marker',
    'chart.dashes': 'Dashes',
    'chart.date_tooltip': 'Date Tooltip',
    'chart.animation': 'Animation',
    'filter.station': 'Station',
    'filter.start_date': 'Start Date',
    'filter.end_date': 'End Date',
    'live.live_data': 'Live Data',
    'live.last_day': 'Last Day',
    'live.last_week': 'Last Week',
    'live.last_month': 'Last Month',
    'live.last_year': 'Last Year',
    'live.customize': 'Customize',
    'live.date_time': 'Date & Time',
    'live.humidity': 'Humidity',
    'live.co': 'CO',
    'live.co2': 'CO2',
    'live.o3': 'O3',
    'live.no2': 'NO2',
    'live.so2': 'SO2',
    'live.pm2.5': 'PM2.5',
    'live.pm10': 'PM10',
    'live.ch4': 'CH4',
    'live.h2s': 'H2S',
    'live.nmhc': 'NMHC',
    'live.fujairah_port': 'Fujairah Port',
    'live.fujairah_stadium': 'Fujairah Stadium',
    'live.sakamkam': 'Sakamkam',
    'datacapture.valid_records': 'No.Of Valid Records',
    'reports.generate_report': 'Generate Report',
    'reports.back_to_filter': 'Back to Filter',
    'reports.download': 'Download',
    'reports.average_reports': 'Average Reports',
    'reports.statistical_reports': 'Statistical Reports',
    'reports.summary_reports': 'Summary Reports',
    'reports.met_reports': 'Met Reports',
    'reports.pollutionrose_reports': 'Pollutionrose Reports',
    'reports.basic_data_export': 'Basic Data Export',
    'reports.average_data_trend_report': 'Average Data Trend Report',
    'reports.concentration_distribution': 'Concentration Distribution',
    'reports.frequency_distribution': 'Frequency Distribution',
    'reports.max_hourly_values': 'Max Hourly Values',
    'reports.network_data_recovery_report': 'Network Data Recovery Report',
    'reports.violation_of_standards': 'Violation of Standards',
    'reports.24_hour_avg_summary_reports': '24 Hour Avg Summary Reports',
    'reports.8_hour_rolling_avg_report': '8 Hour Rolling Avg Report',
    'reports.daily_summary_report': 'Daily Summary Report',
    'reports.monthly_report': 'Monthly Report',
    'reports.windrose_report': 'Windrose Report',
    'reports.pollutionrose_report': 'Pollutionrose Report'
  },
  ar: {
    'nav.dashboard_title': 'لوحة مراقبة جودة الهواء',
    'nav.live_data': 'البيانات المباشرة',
    'nav.analytics': 'التحليلات',
    'nav.reports': 'التقارير',
    'nav.data_summary': 'ملخص البيانات',
    'profile.user_name': 'جهانجير ميان',
    'filter.title': 'تصفية',
    'filter.select_station': 'اختر المحطة',
    'filter.all_stations': 'جميع المحطات',
    'filter.select_parameter': 'اختر المعلمة',
    'filter.all_parameters': 'جميع المعلمات',
    'live.graph_view': 'عرض الرسم البياني',
    'nav.summary': 'الملخص',
    'nav.data_capture': 'معدل التقاط البيانات',
    'nav.back_to_map': 'العودة إلى الخريطة',
    'profile.settings': 'إعدادات الملف الشخصي',
    'profile.help': 'مركز المساعدة',
    'profile.logout': 'تسجيل الخروج',
    'live.title': 'البيانات المباشرة',
    'live.view_type': 'نوع العرض',
    'live.tabular_view': 'عرض جدولي',
    'live.map_view': 'عرض الخريطة',
    'live.grid_view': 'عرض شبكي',
    'live.stations': 'المحطات',
    'live.city_centre': 'مركز المدينة',
    'live.mobile_station': 'المحطة المتنقلة',
    'live.qidfa': 'قدفع',
    'live.lafarge_cems': 'لافارج سيمز',
    'live.date': 'التاريخ',
    'live.today': 'اليوم',
    'live.daily': 'يوميا',
    'live.monthly': 'شهريا',
    'live.yearly': 'سنويا',
    'live.aqi_index': 'مؤشر جودة الهواء',
    'live.moderate': 'معتدل',
    'live.live_aqi': 'مؤشر جودة الهواء المباشر',
    'live.pollutant_metrics': 'مقاييس الملوثات',
    'live.wind_speed': 'سرعة الرياح',
    'live.wind_direction': 'اتجاه الرياح',
    'live.light_breeze': 'نسيم عليل',
    'live.temperature': 'درجة الحرارة',
    'live.ideal_temp': 'درجة حرارة مثالية',
    'live.atmospheric_pressure': 'الضغط الجوي',
    'live.balanced_pressure': 'ضغط هواء متوازن',
    'live.solar_radiation': 'الإشعاع الشمسي',
    'live.high_solar': 'كثافة شمسية عالية',
    'live.relative_humidity': 'الرطوبة النسبية',
    'live.humidity_normal': 'الرطوبة طبيعية',
    'live.fujairah': 'الفجيرة',
    'analytics.parameters': 'المعلمات',
    'analytics.report_type': 'نوع التقرير',
    'analytics.daily_summary': 'الملخص اليومي',
    'analytics.hourly_summary': 'الملخص كل ساعة',
    'analytics.min': 'الأدنى',
    'analytics.max': 'الأقصى',
    'analytics.avg': 'المتوسط',
    'analytics.download': 'تنزيل',
    'datacapture.title': 'معدل التقاط البيانات',
    'datacapture.tab1': 'معدل التقاط البيانات',
    'datacapture.tab2': 'التقاط البيانات الصالحة',
    'datacapture.collected_records': 'عدد السجلات المجمعة',
    'datacapture.valid_records': 'عدد السجلات الصالحة',
    'datacapture.sno': 'م.',
    'datacapture.station_name': 'اسم المحطة',
    'datacapture.parameter': 'المعلمة',
    'datacapture.expected_records': 'عدد السجلات المتوقعة',
    'datacapture.percent_avail': 'نسبة التوفر',
    'login.title': 'تسجيل الدخول',
    'login.subtitle': 'الرجاء إدخال بياناتك.',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.remember_me': 'تذكرني',
    'login.forgot_password': 'هل نسيت كلمة المرور؟',
    'login.no_account': 'ليس لديك حساب؟',
    'login.sign_up': 'التسجيل',
    'login.firstName': 'الاسم الأول',
    'login.lastName': 'الاسم الأخير',
    'login.phoneNumber': 'رقم الهاتف',
    'login.emiratesId': 'رقم الهوية الإماراتية',
    'login.emiratesIdPlaceholder': '784-XXXX-XXXXXXX-X',
    'login.firstNamePlaceholder': 'أدخل الاسم الأول',
    'login.lastNamePlaceholder': 'أدخل الاسم الأخير',
    'login.emailPlaceholder': 'أدخل البريد الإلكتروني',
    'login.phoneNumberPlaceholder': 'أدخل رقم الهاتف',
    'login.joinPlatform': 'انضم إلى منصتنا',
    'login.createAnAccount': 'إنشاء حساب',
    'login.alreadyHaveAccount': 'هل لديك حساب بالفعل؟',
    'login.forgotPasswordTitle': 'نسيت كلمة المرور',
    'login.forgotPasswordSubtitle': 'أدخل بريدك الإلكتروني لتلقي رمز التحقق',
    'login.sendOtp': 'إرسال رمز التحقق',
    'login.backToLogin': 'العودة إلى تسجيل الدخول',
    'login.enterYourPasscode': 'أدخل رمز التحقق',
    'login.otpSentSubtitle': 'لقد أرسلنا رمز التحقق إلى بريدك الإلكتروني',
    'login.codeExpiresIn': 'تنتهي صلاحية الرمز خلال',
    'login.didNotReceiveCode': 'لم تستلم الرمز؟',
    'login.resendCode': 'إعادة إرسال الرمز',
    'login.verify': 'التحقق',
    'login.newPassword': 'كلمة المرور الجديدة',
    'login.confirmPassword': 'تأكيد كلمة المرور',
    'login.updatePassword': 'تحديث كلمة المرور',
    'login.resetPasswordTitle': 'إعادة تعيين كلمة المرور',
    'login.resetPasswordSubtitle': 'أدخل كلمة المرور الجديدة أدناه',
    'dropdown.none': 'لا شيء',
    'landing.nav.our_air_quality': 'جودة الهواء لدينا',
    'landing.nav.live_air_quality': 'جودة الهواء المباشرة',
    'landing.nav.contact_us': 'اتصل بنا',
    'landing.hero.title': 'مراقبة جودة الهواء في الوقت الفعلي',
    'landing.hero.subtitle': 'لإمارة الفجيرة',
    'landing.hero.view_live': 'عرض المؤشر المباشر',
    'landing.stats.current_aqi': 'المؤشر الحالي',
    'landing.stats.good': 'جيد',
    'landing.stats.active_stations': 'المحطات النشطة',
    'landing.stats.monitoring': 'مراقبة',
    'landing.stats.coverage_area': 'منطقة التغطية',
    'landing.stats.fujairah': 'الفجيرة',
    'landing.map.title': 'خريطة جودة الهواء المباشرة',
    'landing.map.desc': 'استكشف مقاييس جودة الهواء في الوقت الفعلي في إمارة الفجيرة.',
    'landing.map.city_centre': 'المحطات',
    'landing.map.aqi_index': 'مؤشر جودة الهواء',
    'landing.map.primary': 'أساسي',
    'landing.map.secondary': 'ثانوي',
    'landing.map.weather': 'الطقس',
    'landing.map.last_updated': 'آخر تحديث',
    'landing.dash.safety_level': 'مستوى سلامة جودة الهواء',
    'landing.dash.pollutant': 'الملوث الرئيسي المساهم',
    'landing.dash.suburban': 'حركة المرور في الضواحي',
    'landing.dash.natural': 'المصادر الطبيعية',
    'landing.dash.causes': 'الأسباب / الأنشطة المحتملة',
    'landing.dash.measures': 'التدابير الوقائية',
    'landing.dash.trend': 'اتجاه المؤشر كل ساعة',
    'landing.dash.moderate': 'معتدل',
    'landing.dash.unhealthy_sg': 'غير صحي للمجموعات الحساسة',
    'landing.dash.unhealthy': 'غير صحي',
    'landing.dash.very_unhealthy': 'غير صحي للغاية',
    'landing.dash.hazardous': 'خطير',
    'landing.dash.pm10': 'الجسيمات الدقيقة PM10',
    'landing.dash.respirable': 'الغبار القابل للتنفس',
    'landing.dash.measures.windows': 'أغلق النوافذ',
    'landing.dash.measures.outdoor': 'تقليل الأنشطة الخارجية',
    'landing.dash.measures.mask': 'ارتداء كمامة N95',
    'landing.dash.measures.purifier': 'استخدم منقي الهواء',
    'landing.footer.copyright': '© 2026 AQMS الفجيرة. جميع الحقوق محفوظة.',
    'landing.footer.terms': 'شروط الخدمة',
    'landing.footer.privacy': 'سياسة الخصوصية',
    'landing.footer.support': 'الدعم',
    'chart.optimize_large_datasets': 'تحسين مجموعات البيانات الكبيرة',
    'chart.showing_all_points': 'عرض جميع النقاط',
    'chart.max_points_optimized': 'أقصى عدد من النقاط (المحسنة)',
    'chart.marker': 'العلامات',
    'chart.dashes': 'خطوط متقطعة',
    'chart.date_tooltip': 'تلميح التاريخ',
    'chart.animation': 'الحركة',
    'filter.station': 'المحطة',
    'filter.start_date': 'تاريخ البدء',
    'filter.end_date': 'تاريخ الانتهاء',
    'live.live_data': 'البيانات المباشرة',
    'live.last_day': 'آخر يوم',
    'live.last_week': 'آخر أسبوع',
    'live.last_month': 'آخر شهر',
    'live.last_year': 'آخر عام',
    'live.customize': 'تخصيص',
    'live.date_time': 'التاريخ والوقت',
    'live.humidity': 'الرطوبة',
    'live.co': 'CO',
    'live.co2': 'CO2',
    'live.o3': 'O3',
    'live.no2': 'NO2',
    'live.so2': 'SO2',
    'live.pm2.5': 'PM2.5',
    'live.pm10': 'PM10',
    'live.ch4': 'CH4',
    'live.h2s': 'H2S',
    'live.nmhc': 'NMHC',
    'live.fujairah_port': 'ميناء الفجيرة',
    'live.fujairah_stadium': 'إستاد الفجيرة',
    'live.sakamkam': 'سقمقم',
    'datacapture.valid_records': 'عدد السجلات الصالحة',
    'reports.generate_report': 'إنشاء التقرير',
    'reports.back_to_filter': 'العودة إلى التصفية',
    'reports.download': 'تنزيل',
    'reports.average_reports': 'تقارير المتوسطات',
    'reports.statistical_reports': 'التقارير الإحصائية',
    'reports.summary_reports': 'تقارير الملخصات',
    'reports.met_reports': 'تقارير الأرصاد الجوية',
    'reports.pollutionrose_reports': 'تقارير وردة التلوث',
    'reports.basic_data_export': 'تصدير البيانات الأساسية',
    'reports.average_data_trend_report': 'تقرير اتجاه متوسط البيانات',
    'reports.concentration_distribution': 'توزيع التركيز',
    'reports.frequency_distribution': 'توزيع التكرار',
    'reports.max_hourly_values': 'أقصى القيم الساعية',
    'reports.network_data_recovery_report': 'تقرير استعادة بيانات الشبكة',
    'reports.violation_of_standards': 'مخالفة المعايير',
    'reports.24_hour_avg_summary_reports': 'تقارير ملخص متوسط 24 ساعة',
    'reports.8_hour_rolling_avg_report': 'تقرير المتوسط المتحرك لـ 8 ساعات',
    'reports.daily_summary_report': 'تقرير الملخص اليومي',
    'reports.monthly_report': 'التقرير الشهري',
    'reports.windrose_report': 'تقرير وردة الرياح',
    'reports.pollutionrose_report': 'تقرير وردة التلوث'
  }
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('appLanguage', lang);
  }, [lang]);

  const toggleLanguage = () => {
    setLang(prev => (prev === 'en' ? 'ar' : 'en'));
  };

  const t = (key, fallback) => {
    return translations[lang][key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
